
# Edit with your actual paths
fastq_R1: G:\Otogelin\OTOG\1\wes-proband\data\fastq>Proband_R1.fastq.gz
fastq_R2: G:\Otogelin\OTOG\1\wes-proband\data\fastq>Proband_R2.fastq.gz
sample_id: PROBAND
reference_fasta: G:\Otogelin\OTOG\1\wes-proband\data\refs>
known_sites:
  - G:/Otogelin/OTOG/1/wes-pipeline/ref/known_sites/Homo_sapiens_assembly38.dbsnp138.vcf.gz
  - G:/Otogelin/OTOG/1/wes-pipeline/ref/known_sites/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  - G:/Otogelin/OTOG/1/wes-pipeline/ref/known_sites/1000G_phase1.snps.high_confidence.hg38.vcf.gz
  - G:/Otogelin/OTOG/1/wes-pipeline/ref/known_sites/1000G_phase1.indels.hg38.vcf.gz
threads: 16
outdir: ./results
