
# Edit with your actual paths
fastq_R1: /path/to/sample_R1.fastq.gz
fastq_R2: /path/to/sample_R2.fastq.gz
sample_id: PROBAND
reference_fasta: /path/to/GRCh38.fa
known_sites:
  - /path/to/dbsnp_151.hg38.vcf.gz
  - /path/to/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  - /path/to/1000G_phase1.snps.high_confidence.hg38.vcf.gz
  - /path/to/1000G_phase1.indels.hg38.vcf.gz
threads: 16
outdir: ./results
